version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dianabot_postgres
    environment:
      POSTGRES_DB: dianabot
      POSTGRES_USER: dianabot_user
      POSTGRES_PASSWORD: dianabot_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dianabot_user -d dianabot"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:6
    container_name: dianabot_mongodb
    environment:
      MONGO_INITDB_DATABASE: dianabot
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/dianabot --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: dianabot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: dianabot_app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dianabot
      - POSTGRES_USER=dianabot_user
      - POSTGRES_PASSWORD=dianabot_password
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=dianabot
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  celery:
    build: .
    container_name: dianabot_celery
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dianabot
      - POSTGRES_USER=dianabot_user
      - POSTGRES_PASSWORD=dianabot_password
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=dianabot
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: celery -A tasks.celery_app worker --loglevel=info

volumes:
  postgres_data:
  mongodb_data:
  redis_data: